export const voiceNameMap = [
  { code: 'es', name: 'es-ES-ElviraNeural', LangCode: 'es-ES' },
  { code: 'en', name: 'en-US-AriaNeural', LangCode: 'en-US' },
  { code: 'fr', name: 'fr-FR-Denise-AzureNeural', LangCode: 'fr-FR' },
  { code: 'de', name: 'de-DE-KatjaNeural', LangCode: 'de-DE' },
  { code: 'it', name: 'it-IT-ElsaNeural', LangCode: 'it-IT' },
  { code: 'ja', name: 'ja-JP-NanamiNeural', LangCode: 'ja-JP' },
  { code: 'ko', name: 'ko-KR-SunHiNeural', LangCode: 'ko-KR' },
  { code: 'pt', name: 'pt-BR-FranciscaNeural', LangCode: 'pt-BR' },
  { code: 'ru', name: 'ru-RU-Svetlana-AzureNeural', LangCode: 'ru-RU' },
  { code: 'zh', name: 'zh-CN-XiaoxiaoNeural', LangCode: 'zh-CN' },
  { code: 'ar', name: 'ar-TN-ReemNeural', LangCode: 'ar-EG' },
  { code: 'hi', name: 'hi-IN-MadhurNeural', LangCode: 'hi-IN' },
  { code: 'tr', name: 'tr-TR-EmelNeural', LangCode: 'tr-TR' },
  { code: 'nl', name: 'nl-NL-ColetteNeural', LangCode: 'nl-NL' },
  { code: 'id', name: 'id-ID-ArdiNeural', LangCode: 'id-ID' },
  { code: 'pl', name: 'pl-PL-AgnieszkaNeural', LangCode: 'pl-PL' },
  { code: 'cs', name: 'cs-CZ-VlastaNeural', LangCode: 'cs-CZ' },
  { code: 'da', name: 'da-DK-HelleNeural', LangCode: 'da-DK' },
  { code: 'fi', name: 'fi-FI-SelmaNeural', LangCode: 'fi-FI' },
  { code: 'hu', name: 'hu-HU-NoemiNeural', LangCode: 'hu-HU' },
];
